In [3]:
pip install lxml

Collecting lxml
  Downloading https://files.pythonhosted.org/packages/55/6f/c87dffdd88a54dd26a3a9fef1d14b6384a9933c455c54ce3ca7d64a84c88/lxml-4.5.1-cp36-cp36m-manylinux1_x86_64.whl (5.5MB)
     |████████████████████████████████| 5.5MB 5.6MB/s eta 0:00:01     |████▍                           | 757kB 5.6MB/s eta 0:00:01     |████████▎                       | 1.4MB 5.6MB/s eta 0:00:01
Installing collected packages: lxml
Successfully installed lxml-4.5.1
Note: you may need to restart the kernel to use updated packages.

In [4]:
pip install beautifulsoup4

Collecting beautifulsoup4
  Downloading https://files.pythonhosted.org/packages/66/25/ff030e2437265616a1e9b25ccc864e0371a0bc3adb7c5a404fd661c6f4f6/beautifulsoup4-4.9.1-py3-none-any.whl (115kB)
     |████████████████████████████████| 122kB 6.3MB/s eta 0:00:01
Collecting soupsieve>1.2 (from beautifulsoup4)
  Downloading https://files.pythonhosted.org/packages/6f/8f/457f4a5390eeae1cc3aeab89deb7724c965be841ffca6cfca9197482e470/soupsieve-2.0.1-py3-none-any.whl
Installing collected packages: soupsieve, beautifulsoup4
Successfully installed beautifulsoup4-4.9.1 soupsieve-2.0.1
Note: you may need to restart the kernel to use updated packages.

In [5]:
pip install html5lib

Requirement already satisfied: html5lib in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (0.9999999)
Requirement already satisfied: six in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (from html5lib) (1.15.0)
Note: you may need to restart the kernel to use updated packages.

In [6]:
pip install requests

Requirement already satisfied: requests in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (2.23.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (from requests) (2020.4.5.2)
Requirement already satisfied: chardet<4,>=3.0.2 in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (from requests) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (from requests) (1.25.9)
Requirement already satisfied: idna<3,>=2.5 in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (from requests) (2.9)
Note: you may need to restart the kernel to use updated packages.

In [1]:
#from bs4 import BeautifulSoup
#import requests
import csv
import pandas as pd
import urllib.request
import re
import matplotlib.pyplot as plt

In [15]:
masterlink = 'https://www.mohfw.gov.in/#state-data'
mastersource = requests.get(masterlink).text
mastersoup = BeautifulSoup(mastersource,'lxml')
table = mastersoup.find('tbody')
print(table)
#print(mastersoup.prettify())

In [29]:

for alpha in table.find_all('tr'):
    row = ""
    for bravo in alpha.find_all('td'):
        row = row + bravo.text + ","
    print(row)

1,Andaman and Nicobar Islands,31,45,0,76,
2,Andhra Pradesh,7164,5908,169,13241,
3,Arunachal Pradesh,121,60,1,182,
4,Assam,2108,5088,10,7206,
5,Bihar,2034,7118,60,9212,
6,Chandigarh,87,336,6,429,
7,Chhattisgarh,558,2091,13,2662,
8,Dadra and Nagar Haveli and Daman and Diu,118,60,0,178,
9,Delhi,27847,52607,2623,83077,
10,Goa,717,478,3,1198,
11,Gujarat,6712,22800,1808,31320,
12,Haryana,4689,8917,223,13829,
13,Himachal Pradesh,378,529,9,916,
14,Jammu and Kashmir,2683,4316,94,7093,
15,Jharkhand,559,1793,12,2364,
16,Karnataka,5476,7507,207,13190,
17,Kerala,2015,2152,22,4189,
18,Ladakh,376,586,1,963,
19,Madhya Pradesh,2545,10084,557,13186,
20,Maharashtra,70622,86575,7429,164626,
21,Manipur,730,455,0,1185,
22,Meghalaya,4,42,1,47,
23,Mizoram,93,55,0,148,
24,Nagaland,251,164,0,415,
25,Odisha,1850,4743,21,6614,
26,Puducherry,388,221,10,619,
27,Punjab,1557,3526,133,5216,
28,Rajasthan,3261,13611,399,17271,
29,Sikkim,39,49,0,88,
30,Tamil Nadu,35659,45537,1079,82275,
31,Telangana,9000,5172,247,14419,
32,Tripura,266,1079,1,1346,
33,Uttarakhand,767,2018,38,2823,
34,Uttar Pradesh,6679,14808,660,22147,
35,West Bengal,5451,11193,639,17283,
,Cases being reassigned to states,7285,,,7285,
,Total#,210120,
321723
,
16475
,
548318
,
*(Including foreign Nationals)

,
**( more than 70% cases due to comorbidities )
,
#States wise distribution is subject to further verification and reconciliation
,
#Our figures are being reconciled with ICMR,

In [28]:
df = pd.read_csv('COVID State DATA.csv')
df

,S. No.,Name of State / UT,Active Cases*,Cured/Discharged/Migrated*,Deaths**,Total Confirmed cases*
0,1,Andaman and Nicobar Islands,31.0,45.0,0,76.0
1,2,Andhra Pradesh,7164.0,5908.0,169,13241.0
2,3,Arunachal Pradesh,121.0,60.0,1,182.0
3,4,Assam,2108.0,5088.0,10,7206.0
4,5,Bihar,2034.0,7118.0,60,9212.0
5,6,Chandigarh,87.0,336.0,6,429.0
6,7,Chhattisgarh,558.0,2091.0,13,2662.0
7,8,Dadra and Nagar Haveli and Daman and Diu,118.0,60.0,0,178.0
8,9,Delhi,27847.0,52607.0,2623,83077.0
9,10,Goa,717.0,478.0,3,1198.0
10,11,Gujarat,6712.0,22800.0,1808,31320.0
11,12,Haryana,4689.0,8917.0,223,13829.0
12,13,Himachal Pradesh,378.0,529.0,9,916.0
13,14,Jammu and Kashmir,2683.0,4316.0,94,7093.0
14,15,Jharkhand,559.0,1793.0,12,2364.0
15,16,Karnataka,5476.0,7507.0,207,13190.0
16,17,Kerala,2015.0,2152.0,22,4189.0
17,18,Ladakh,376.0,586.0,1,963.0
18,19,Madhya Pradesh,2545.0,10084.0,557,13186.0
19,20,Maharashtra,70622.0,86575.0,7429,164626.0
20,21,Manipur,730.0,455.0,0,1185.0
21,22,Meghalaya,4.0,42.0,1,47.0
22,23,Mizoram,93.0,55.0,0,148.0
23,24,Nagaland,251.0,164.0,0,415.0
24,25,Odisha,1850.0,4743.0,21,6614.0
25,26,Puducherry,388.0,221.0,10,619.0
26,27,Punjab,1557.0,3526.0,133,5216.0
27,28,Rajasthan,3261.0,13611.0,399,17271.0
28,29,Sikkim,39.0,49.0,0,88.0
29,30,Tamil Nadu,35659.0,45537.0,1079,82275.0
30,31,Telangana,9000.0,5172.0,247,14419.0
31,32,Tripura,266.0,1079.0,1,1346.0
32,33,Uttarakhand,767.0,2018.0,38,2823.0
33,34,Uttar Pradesh,6679.0,14808.0,660,22147.0
34,35,West Bengal,5451.0,11193.0,639,17283.0
35,Cases being reassigned to states,7285,NaN,NaN,7285,NaN
36,Total#,210120,321723.0,16475.0,548318,NaN